server:
  port: 8092
  servlet:
    session:
      timeout: 10
     
spring :
   application :
      name : orderService  
   zipkin:
     base-url: http://localhost:7777
     locator:
        discovery:
            enabled: true
   sleuth:
    sampler:
      probability: 1.0
    web:  
           skipPattern : (^cleanup.*)     
 
   datasource:
      driver-class-name: com.mysql.jdbc.Driver

      url: jdbc:mysql://localhost:3306/order?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8

      username: root
      password: 1234


#### mybatis配置
mybatis:
  #mapper.xml所在位置
  mapper-locations: classpath:mapping/*.xml
  #实体类所做包
  type-aliases-package: com.jd.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
             
eureka:
  client:
    serviceUrl:
      default-zone: http://localhost:8761/eureka/
      
feign:
  hystrix:
    enabled: true